# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-149140730-1'

menu:
- {name: 'Publications', path: 'menu', url: 'https://scholar.google.com/citations?hl=en&view_op=list_works&gmla=AJsN-F6ardClNeVznBH90alLFyb9W49tnlQGI6dMfq16eHYjbJrtXWRy8KMPt1X6xCSvGK-vILRJrvUmyJMi1VjdXajAfqC05XANUyyW38447hn-ynrQIec&user=Wr_6CE8AAAAJ'}
# - {name: 'CV', path: 'menu', url: '../files/Andrew_Jones_CV.pdf'}
- {name: 'Technical blog', path: 'menu', url: 'blog.html'}
# - {name: 'Essays', path: 'menu', url: 'essays.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'github', link: 'https://github.com/andrewcharlesjones'}
# - {icon: 'graduation-cap', link: 'https://scholar.google.com/citations?hl=en&view_op=list_works&gmla=AJsN-F6ardClNeVznBH90alLFyb9W49tnlQGI6dMfq16eHYjbJrtXWRy8KMPt1X6xCSvGK-vILRJrvUmyJMi1VjdXajAfqC05XANUyyW38447hn-ynrQIec&user=Wr_6CE8AAAAJ'}
# - {icon: 'twitter', link: 'https://twitter.com/andy_c_jones'}

# - {icon: 'linkedin', link: ''}
- {icon: 'envelope', link: 'ajones788@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

# sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy:'

# post_date_prefix: 'Written on'
